---

require:
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'db/**/*'
    - 'lib/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'gemfiles/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/BlockLength:
  Max: 150
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 128

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  AllowedPatterns: ['change']
