---

require:
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'db/**/*'
    - 'lib/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'gemfiles/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/BlockLength:
  Max: 150
  Exclude:
    - spec/**/*
    - lib/**/*

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 170

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  AllowedPatterns: ['change']
